### PR TITLE
Replace `lua` codeblocks with `luau`

### PR DESCRIPTION
**Pull request by joonyoo181**
We support luau code blocks now! Let's switch over to it :)

### CODE REVIEW

**Review by vegorov-rbx — CHANGES_REQUESTED** [review]
Not sure how you tested it, but it breaks all code blocks on the website.

**Comment by joonyoo181** [comment]
> Not sure how you tested it, but it breaks all code blocks on the website.

The way I tested was by looking at the previews of the .md files and seeing that the codeblocks look the same as the ones from the [recent recap](https://luau-lang.org/2024/07/23/luau-recap-july-2024.html). But now rereading the recent recap, the codeblocks there seem to be broken as well?

**Comment by vegorov-rbx** [comment]
Yes, recent one is broken, so a better PR would be to switch any luau blocks to lua.

**Comment by joonyoo181** [comment]
> Yes, recent one is broken, so a better PR would be to switch any luau blocks to lua.

Ah got it, will do!

**Pull request closed without merging**
